# Generated by Django 2.2.5 on 2019-12-29 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分类名称', max_length=50, unique=True)),
                ('code', models.CharField(help_text='代码编号', max_length=30, unique=True)),
            ],
            options={
                'verbose_name': '应用分类',
                'verbose_name_plural': '应用分类',
                'db_table': 'ts_apptags',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=50, unique=True)),
                ('introduction', models.TextField(verbose_name='项目简介')),
                ('state', models.SmallIntegerField(choices=[(0, '提测中'), (1, '开发中'), (2, '测试中'), (3, '已上线'), (4, '已下线')], default=0, help_text='app的开发状态')),
                ('language', models.SmallIntegerField(choices=[(0, 'Python'), (1, 'Java'), (2, 'PHP')], default=0, help_text='应用开发语言')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='apilogo')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, help_text='创建者', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ForeignKey(blank=True, help_text='项目标签', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.AppTags')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
                'db_table': 'ts_project',
            },
        ),
        migrations.CreateModel(
            name='ProjectEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environ', models.IntegerField(choices=[(1001, '本地环境'), (1002, '测试环境'), (1003, '验收环境'), (1004, '生产环境')], default=1001, verbose_name='项目环境')),
                ('domain', models.URLField(max_length=100, verbose_name='域名')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目环境域名配置',
                'verbose_name_plural': '项目环境域名配置',
                'db_table': 'ts_project_environ',
            },
        ),
    ]
