# Generated by Django 2.2 on 2020-05-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(db_index=True, default=b'\xa1\xc3K\x86mN\xa9\x81\x86\xe0', max_length=50, verbose_name='项目code'),
        ),
        migrations.AddField(
            model_name='project',
            name='creator_name',
            field=models.CharField(default=1, max_length=30, verbose_name='创建者姓名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='introduction',
            field=models.CharField(max_length=100, verbose_name='项目简介'),
        ),
    ]
