# Generated by Django 2.2 on 2020-05-24 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
        ('project', '0002_auto_20200524_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(db_index=True, default='69505f3174de40eda96b', max_length=50, verbose_name='项目code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.SmallIntegerField(choices=[(1, '开发中'), (0, '提测中'), (2, '测试中'), (3, '已上线'), (4, '已下线')], default=0, help_text='app的开发状态'),
        ),
        migrations.CreateModel(
            name='ProjectMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='人员姓名')),
                ('permissionType', models.CharField(choices=[(0, '管理员'), (1, '开发人员'), (2, '测试人员')], max_length=50, verbose_name='权限角色')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile', verbose_name='人员信息')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_project', to='project.Project', verbose_name='所属项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目成员配置',
                'verbose_name_plural': '项目成员配置',
                'db_table': 'ts_project_members',
            },
        ),
    ]
