# Generated by Django 2.2 on 2020-05-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200524_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectenvironment',
            name='project_name',
            field=models.CharField(default=1, max_length=50, verbose_name='项目名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(db_index=True, default='5d9a515b36694aecb65b', max_length=50, verbose_name='项目code'),
        ),
    ]
