# Generated by Django 2.2 on 2020-05-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200524_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(db_index=True, default='575427e94ab3a62486ef', max_length=50, verbose_name='项目code'),
        ),
    ]
